name: Release

on:
  pull_request:
    branches:
      - main  # 指定觸發的分支
    types:
      - closed  # 只在 PR 被關閉時觸發
#  push:
#    branches:
#      - main

jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    name: Release
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1
      - name: Install dependencies
        run: npm ci
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
